version: "3"

services:
  strapi:
    container_name: tc1-strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=tc1-strapi-2023a.h6bsiwy.mongodb.net
      - DATABASE_PORT=27017
      - DATABASE_SSL=true
      - DATABASE_SRV=true
      - DATABASE_NAME=tc1-strapi-2023A
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin123
    ports:
      - 1337:1337